### ISSUE TITLE
Poll is not registering votes anymore

### ISSUE THREAD

**Issue by parcae** [KazuAlex/openpollslack#5] opened 2019-12-08 19:34 UTC
We are using the openpoll for a few months now, but since the beginning of this week the votes are not registered anymore. The poll is displayed and we can press the vote buttons, but no votes are registered.

**Comment by KazuAlex** [comment] 2019-12-09 13:03
Hello, i currently investigate on this.
It will be fixed in few hours

**Closed** 2019-12-09 13:13 UTC

**Comment by KazuAlex** [comment] 2019-12-09 13:15
Hi @parcae ,

The issue is now resolved. Thanks for the usage of this app

Regards

**Comment by parcae** [comment] 2019-12-09 13:40
Thanks, just checked it and indeed it works! :)
